image: k33g/wasm-university-training:0.0.6

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env 
      wasmedge --version
      #cd 15-go-wasmedge-cli/
      #go get github.com/second-state/WasmEdge-go/wasmedge@v0.10.0


    init: |
      echo "🚀 initialize"
      npm install
      export DOTNET_ROOT=$HOME/dotnet
      export PATH=$PATH:$HOME/dotnet
      #dotnet add package Wasi.Sdk --prerelease
      dotnet --version

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments
    - grain-lang.vscode-grain
    - ms-dotnettools.vscode-dotnet-runtime
