---
# The container image exists on the GitLab registry
image: registry.gitlab.com/wasmuniversity/images/wasm-go-rust:0.0.2

tasks:
  - name: initialize
    before: |
      
      echo "wip"

      # ------------------------------------
      # GoLang
      # ------------------------------------

      #source /home/gitpod/.gvm/scripts/gvm
      #gvm use go1.17.5

      #sudo echo "source /home/gitpod/.gvm/scripts/gvm" >> $HOME/.bashrc
      #sudo echo "gvm use go1.17.5" >> $HOME/.bashrc

      # ------------------------------------
      # wasmer
      # ------------------------------------
      #curl https://get.wasmer.io -sSfL | sh
      #source /home/gitpod/.wasmer/wasmer.sh

      #sudo echo "source /home/gitpod/.wasmer/wasmer.sh" >> $HOME/.bashrc

      # ------------------------------------
      # wasmtime
      # ------------------------------------
      #curl https://wasmtime.dev/install.sh -sSf | bash
      #source $HOME/.bashrc

      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      #wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.9.0
      #source /home/gitpod/.wasmedge/env 
      #sudo echo "source /home/gitpod/.wasmedge/env" >> $HOME/.bashrc
      #go get github.com/second-state/WasmEdge-go/wasmedge@v0.9.0

    init: |

      npm install

ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - golang.go
    - aaron-bond.better-comments
